import { Event, SeatSection, Order } from './types'

// Deterministic pseudo-random: avoids SSR/client hydration mismatch (BUG-07)
const fakeRand = (i: number, j: number, seed: number) =>
  ((i * 31 + j * 17 + seed * 7) % 97) / 97

export const mockEvents: Event[] = [
  {
    id: '8',
    title: '回音樹 AI 歌手 爵士女伶 Ann — 夜之旋律',
    artist: 'Ann（回音樹 AI 歌手）',
    venue: '台北 Legacy Taipei',
    city: '台北',
    date: '2026-06-14',
    time: '20:00',
    image: '/ann-jazz-singer.jpg',
    category: 'concert',
    priceFrom: 1200,
    priceTo: 3600,
    totalSeats: 800,
    availableSeats: 560,
    status: 'on-sale',
    tags: ['熱門', '爵士', 'AI歌手'],
    imagePosition: '50% 20%',
  },
  {
    id: '9',
    title: '林俊杰 JJ LIN 幸存者 巡迴演唱會 台北站',
    artist: '林俊杰 JJ Lin',
    venue: '台北大巨蛋',
    city: '台北',
    date: '2026-09-05',
    time: '19:30',
    image: 'https://img.youtube.com/vi/NDP7sBTO_HU/maxresdefault.jpg',
    category: 'concert',
    priceFrom: 1800,
    priceTo: 6800,
    totalSeats: 40000,
    availableSeats: 12000,
    status: 'on-sale',
    tags: ['熱門', '快售完', '星光'],
    videoId: 'NDP7sBTO_HU',
  },
  {
    id: '7',
    title: 'PSY 江南大叔 濕身系列 WORLD TOUR',
    artist: 'PSY (朴載相)',
    venue: '台北大巨蛋',
    city: '台北',
    date: '2026-07-18',
    time: '19:00',
    image: 'https://img.youtube.com/vi/QAc2-WVUbC8/maxresdefault.jpg',
    category: 'concert',
    priceFrom: 1800,
    priceTo: 6800,
    totalSeats: 40000,
    availableSeats: 28000,
    status: 'on-sale',
    tags: ['熱門', 'K-POP', '濕身'],
    videoId: 'QAc2-WVUbC8',
  },
  {
    id: '1',
    title: '2026 念念不忘必有回音 回音樹ESG音樂節',
    artist: '回音樹',
    venue: '大安森林公園露天音樂台',
    city: '台北',
    date: '2026-05-02',
    time: '14:00',
    image: '/image-1776910203160.jpg',
    category: 'festival',
    priceFrom: 980,
    priceTo: 2800,
    totalSeats: 5000,
    availableSeats: 3200,
    status: 'on-sale',
    tags: ['ESG', '戶外', '熱門'],
    videoId: 'iLQTVMjdzvY',
  },
  {
    id: '2',
    title: 'BORN PINK WORLD TOUR',
    artist: 'BLACKPINK',
    venue: '高雄巨蛋',
    city: '高雄',
    date: '2025-09-20',
    time: '18:00',
    image: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80',
    category: 'concert',
    priceFrom: 2200,
    priceTo: 8800,
    totalSeats: 15000,
    availableSeats: 3200,
    status: 'on-sale',
    tags: ['快售完', 'K-POP'],
    videoId: 'bo_efYLyPkc',
  },
  {
    id: '3',
    title: '草東沒有派對巡迴',
    artist: '草東沒有派對',
    venue: '台中洲際棒球場',
    city: '台中',
    date: '2025-10-05',
    time: '19:00',
    image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=80',
    category: 'concert',
    priceFrom: 1200,
    priceTo: 3600,
    totalSeats: 8000,
    availableSeats: 5600,
    status: 'on-sale',
    tags: ['獨立音樂'],
    videoId: 'uSD4vsh1zDA',
  },
  {
    id: '4',
    title: '2025 跨年晚會',
    artist: '多組藝人',
    venue: '台北市政府廣場',
    city: '台北',
    date: '2025-12-31',
    time: '20:00',
    image: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800&q=80',
    category: 'festival',
    priceFrom: 800,
    priceTo: 2400,
    totalSeats: 20000,
    availableSeats: 18000,
    status: 'coming-soon',
    tags: ['跨年', '即將開賣'],
  },
  {
    id: '5',
    title: 'Mayday 五月天演唱會',
    artist: '五月天',
    venue: '台北大巨蛋',
    city: '台北',
    date: '2025-11-08',
    time: '19:00',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80',
    category: 'concert',
    priceFrom: 1500,
    priceTo: 5800,
    totalSeats: 40000,
    availableSeats: 0,
    status: 'sold-out',
    tags: ['已售完'],
    videoId: 'M3C8pHWuHAE',
  },
  {
    id: '6',
    title: 'Jazz in the Park',
    artist: '爵士音樂節',
    venue: '大安森林公園',
    city: '台北',
    date: '2025-07-19',
    time: '17:00',
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80',
    category: 'festival',
    priceFrom: 500,
    priceTo: 1200,
    totalSeats: 3000,
    availableSeats: 1800,
    status: 'on-sale',
    tags: ['戶外', 'Jazz'],
    videoId: 'Sagg08DrO5U',
  },
]

export const mockSections: SeatSection[] = [
  {
    id: 'vip',
    name: 'VIP 區',
    color: '#f59e0b',
    price: 6800,
    totalSeats: 500,
    availableSeats: 120,
    rows: Array.from({ length: 5 }, (_, ri) => ({
      row: String.fromCharCode(65 + ri),
      seats: Array.from({ length: 20 }, (_, si) => ({
        id: `vip-${String.fromCharCode(65 + ri)}-${si + 1}`,
        number: si + 1,
        status: fakeRand(ri, si, 1) > 0.3 ? 'available' : 'sold',
      })),
    })),
  },
  {
    id: 'a',
    name: 'A 區',
    color: '#8b5cf6',
    price: 3800,
    totalSeats: 2000,
    availableSeats: 850,
    rows: Array.from({ length: 10 }, (_, ri) => ({
      row: String.fromCharCode(65 + ri),
      seats: Array.from({ length: 30 }, (_, si) => ({
        id: `a-${String.fromCharCode(65 + ri)}-${si + 1}`,
        number: si + 1,
        status: fakeRand(ri, si, 2) > 0.4 ? 'available' : 'sold',
      })),
    })),
  },
  {
    id: 'b',
    name: 'B 區',
    color: '#3b82f6',
    price: 2200,
    totalSeats: 3000,
    availableSeats: 1800,
    rows: Array.from({ length: 12 }, (_, ri) => ({
      row: String.fromCharCode(65 + ri),
      seats: Array.from({ length: 35 }, (_, si) => ({
        id: `b-${String.fromCharCode(65 + ri)}-${si + 1}`,
        number: si + 1,
        status: fakeRand(ri, si, 3) > 0.5 ? 'available' : 'sold',
      })),
    })),
  },
  {
    id: 'c',
    name: 'C 區',
    color: '#10b981',
    price: 1800,
    totalSeats: 5000,
    availableSeats: 3200,
    rows: Array.from({ length: 15 }, (_, ri) => ({
      row: String.fromCharCode(65 + ri),
      seats: Array.from({ length: 40 }, (_, si) => ({
        id: `c-${String.fromCharCode(65 + ri)}-${si + 1}`,
        number: si + 1,
        status: fakeRand(ri, si, 4) > 0.6 ? 'available' : 'sold',
      })),
    })),
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ORD-2025-001',
    eventId: '1',
    eventTitle: '2025 台北演唱會',
    eventDate: '2025-08-15 19:30',
    eventVenue: '台北大巨蛋',
    seats: [{ section: 'A 區', row: 'C', seat: 15 }],
    totalAmount: 3800,
    status: 'paid',
    createdAt: '2025-04-10',
    ticketCode: 'TK-001-ABC123',
  },
  {
    id: 'ORD-2025-002',
    eventId: '3',
    eventTitle: '草東沒有派對巡迴',
    eventDate: '2025-10-05 19:00',
    eventVenue: '台中洲際棒球場',
    seats: [
      { section: 'B 區', row: 'E', seat: 8 },
      { section: 'B 區', row: 'E', seat: 9 },
    ],
    totalAmount: 4400,
    status: 'paid',
    createdAt: '2025-04-15',
    ticketCode: 'TK-002-XYZ456',
  },
]
